### ISSUE TITLE
Translation for English Doc in Website (英文页面翻译)

### ISSUE THREAD

**Issue by imbajin** [apache/incubator-hugegraph-doc#109]
The content under `content/en/docs` need translate to English (CN -> EN)

- [ ] [rest-api ](https://github.com/apache/incubator-hugegraph-doc/tree/website/content/en/docs/clients/restful-api) doc translation (subtask)
   - [x] vertex-api ()
   - [x] edge-api ()
   - [x] vertex-label-api ()
   - [x] edge-label-api ()
   - [x] index-label-api ()
   - [x] property-key-api ()
   - [x] graphs-api ()
   - [x] gremlin-api ()
   - [x] auth-api ()
   - [x] traverser-api (**core**)
   - [x] schema-api (#214)
   - [x] rank-api (#149 )
   - [x] task-api (#130  )
   - [x] rebuild-api (#130 )
- [x] [config-api](https://github.com/apache/incubator-hugegraph-doc/tree/website/content/en/docs/config) 
   - [x] config-option (#140)
   - [x] config-guide
   - [x] config-https
   - [x] config-auth
- [x] 介绍页(首页) & 下载页翻译 (#121)
- [x] server 文档翻译 (#115)
- [x] loader 文档翻译 (#113)
- [x] hubble 文档翻译 (#117)
- [x] client-quick 文档翻译 (#116)
- [x] client-api 文档翻译 (#122)
- [x] tools 文档翻译 

✅ 文档翻译后, 大家可以参考 [`README`](https://github.com/apache/incubator-hugegraph-doc/blob/website/README.md) 在本地通过 3 步启动一下网站, 看看**实际效果** (hugo 有一些特有语法, 可理解为增强 markdown 语法)

翻译任务示例可参考：https://github.com/apache/incubator-hugegraph-doc/pull/116/files

具体提交代码流程可参考：https://github.com/apache/incubator-hugegraph/blob/master/CONTRIBUTING.md

**Comment by Showave** [comment]
i can translaste hugegraph-server.md -"介绍页 (首页) 翻译"

**Comment by Alita-Nan** [comment]
I can translate hugegraph-server.md - "client文档翻译”

**Comment by Fizell** [comment]
I can translate hugegraph-tools.md - "tool 文档翻译”

**Comment by hxj8059** [comment]
I can translate hugegraph-hubble.md - "hubble文档翻译”

**Comment by imbajin** [comment]
> i can translaste hugegraph-intro.md -"介绍页 (首页) 翻译"

@Showave 可以顺便帮忙把 download 页面简单翻译一下, 另外 Intro 页面更新了一下, 记得先同步一下代码 (确认最新)

**Comment by javeme** [comment]
I will translate client-api doc:
https://github.com/apache/incubator-hugegraph-doc/blob/website/content/en/docs/clients/hugegraph-client.md

**Comment by awsl-dbq** [comment]
let me try rest-api -> `rebuild-api`() part. PR is coming soon .

**Comment by awsl-dbq** [comment]
let me try rest-api -> rank-api

**Comment by JackyYangPassion** [comment]
I will translate gremlin-console.md doc 
PR: #139

**Comment by JackyYangPassion** [comment]
I will translate config-api doc

**Comment by imbajin** [comment]
TODO:  (Need fix)
- [ ] 安装使用部分中英文 Docker [使用](https://www.gitlink.org.cn/glcc/apply)说明不一致, 缺乏 Docker 使用介绍, 且应移除 `BETA` 标记
- [ ] 应该移除不必要的 rocksdb 依赖 gcc 版本检查/新增, 因为 4.3 已经非常远古了, 仅应在 jdk 版本检查处Note 一下
  <img width="977" alt="image" src="https://github.com/apache/incubator-hugegraph-doc/assets/17706099/8abe26e3-116b-4b03-ab97-5549a150a1f1">

**Comment by imbajin** [comment]
Thanks @WhelanLabs to add #219 ~ #224 translation doc 👍🏻

**Comment by 1280019840** [comment]
![1717655653779](https://github.com/apache/incubator-hugegraph-doc/assets/136102971/03ebdf05-d826-4d9b-98c0-1bcaa91e0883)
Model is an internal package model, how should I create it Create a model when using Vertex Using Vertex [any] as a parameter, call Vertex What about Create. WithVertex

**Comment by 1280019840** [comment]
> ![1717655653779](https://private-user-images.githubusercontent.com/136102971/337147892-03ebdf05-d826-4d9b-98c0-1bcaa91e0883.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTYxOTgsIm5iZiI6MTcxNzY1NTg5OCwicGF0aCI6Ii8xMzYxMDI5NzEvMzM3MTQ3ODkyLTAzZWJkZjA1LWQ4MjYtNGQ5Yi05OGMwLTFiY2FhOTFlMDg4My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNjM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzkyMWUyNzE1MWVlM2EwNmE1NTVhOTE3MjVhYjZkZDcxYjgzYmFmMzYzZWE5MGQ4NDQzNDUxOWY5ZWU0YmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z4txvJ6biVg9jaBdXx60xq-fuLvY7KZOFSNNO0nizw0) Model is an internal package model, how should I create it Create a model when using Vertex Using Vertex [any] as a parameter, call Vertex What about Create. WithVertex

![image](https://github.com/apache/incubator-hugegraph-doc/assets/136102971/035fd910-76dc-43ad-9c04-1d7bdbc558f6)
